### PR TITLE
creating functions for employee_requests

### PR DESCRIPTION
**Pull request by jvw3**
# Ticket 

# Description

- Created functions to get all employees, create an employee, get a single employee, delete an employee, and update an employee
- Once Get, post, update, and delete functions are added to the request_handler.py, we can test the functionality via postman.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by TheOlDustyTrail — APPROVED** [review]

**Review by TheOlDustyTrail — APPROVED** [review]
Looks good

**Review by carlydopps — APPROVED** [review]
Looks great! :)

**Review by swparks040 — CHANGES_REQUESTED** [review]
remove/change all commented out code that has reference to Animals.

**Review by swparks040 — APPROVED** [review]
Changes made, approved.

**Pull request merged**
